### ISSUE TITLE
ReferenceError: jest is not defined

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [phenax/react-test-render-fns#1]
/node_modules/react-test-render-fns/build/utils.js
node_modules/react-test-render-fns/build/utils.js:98
  95 | 
  96 | 
  97 | exports.withAct = withAct;
> 98 | var runAllTimers = withAct(jest.runAllTimers);
  99 | exports.runAllTimers = runAllTimers;
View compiled
__webpack_require__
/Users/nbaumgartner/Documents/GitHub/GEG/Web/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;

**Comment by phenax** [comment]
Thank you for reporting this! Unfortunately, this library is pretty outdated. It was made with the intention of bridging the gap between the latest react and enzyme but some time after I made the library, [react-testing-library](https://github.com/testing-library/react-testing-library) became a very respectable standard. I'd suggest going with that instead. I'll be updating the readme.
